### ISSUE TITLE
Add Bower support (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [Bishop92/JavaScript-Data-Structures#2]
Hi,
Your project is very useful, I think you should be to add to [Bower](http://bower.io/) in near future.
Regards.

**Comment by Bishop92** [comment]
The bower support has been added. Thanks to @pratikpandey21.

**Comment by joseluisq** [comment]
Great !
I found the [pull request #3](https://github.com/Bishop92/JavaScript-Data-Structures/pull/3)
Congrats :+1:

**Comment by Bishop92** [comment]
Thanks you for the feedback!
