### ISSUE TITLE
Reducing Complexity of dequeue

### ISSUE THREAD

**Issue by neilmacintyre** [Bishop92/JavaScript-Data-Structures#4]
The complexity for your dequeue is O(n), because it is based of off an array. If it where to instead be in a list it would work at O(1). I will fix this, if it is an issue (not by design) and make a pull request.

**Comment by neilmacintyre** [comment]
This method from [Stephen Morley](http://code.stephenmorley.org/javascript/queues/) would also work...

"Queue.js is implemented using an array, but avoids the expensive shift operation. Instead of shifting an item from the front of the array when it is dequeued, Queue.js increments an internal offset to indicate that there is space at the front of the array. When this space takes up half the array, Queue.js uses the slice function to remove it. Because n items are moved only after n dequeuing operations have occurred, the dequeue function runs in amortised constant time."

**Comment by Bishop92** [comment]
Hei! Thanks for the improvement!
