### ISSUE TITLE
Shouldnt this be (index < 0) instead of (index < -1)?

### ISSUE THREAD

**Issue by sagiavinash** [Bishop92/JavaScript-Data-Structures#6]
https://github.com/Bishop92/JavaScript-Data-Structures/blob/c13dcd7991b84489d92b3959e750d068b6551865/lib/LinkedList/LinkedList.js#L171

**Comment by Bishop92** [comment]
Yes, it should be index < 0 or index <= -1

**Comment by sagiavinash** [comment]
@Bishop92 can i create a PR?

**Comment by Bishop92** [comment]
I've already fix the issue ;) Feel free to pull the changes
